export const SET_MODAL_CONFIG = 'SET_MODAL_CONFIG';
export const CLEAR_MODAL_CONFIG = 'CLEAR_MODAL_CONFIG';
export const SET_MODAL_REF = 'SET_MODAL_REF';
export const SET_MODAL_ICON = 'SET_MODAL_ICON';
export const SET_MODAL_CONFIRM = 'SET_MODAL_CONFIRM';
export const SET_MODAL_CONFIRM_ACTION = 'SET_MODAL_CONFIRM_ACTION';
export const SET_MODAL_FAIL_ACTION = 'SET_MODAL_FAIL_ACTION';
