export const PENDING_START = 'PENDING_START';
export const PENDING_END = 'PENDING_END';
export const PENDING_SUCCESS = 'PENDING_SUCCESS';
export const PENDING_ERROR = 'PENDING_ERROR';
export const CLEAR_PENDING_ERROR = 'CLEAR_PENDING_ERROR';
